### ISSUE TITLE
subscription fails to get created

### ISSUE THREAD

**Issue by oising** [davidfowl/EventGridDemo#2]
![image](https://github.com/user-attachments/assets/3dc682f5-abc8-4597-95ea-f4604d4d3ee4)

**Comment by davidfowl** [comment]
Oh wait, is this trying to use the resource for local dev?

**Comment by davidfowl** [comment]
This makes sense then. That would only work with something like a dev tunnel or ngrok or something like this.

**Comment by oising** [comment]
Doh, of course. I just got back from a near month-long vacation. Of course this needs ngrok/devtunnel.
